INSERT INTO PROJECT
(TITLE, DESCRIPTION, REQUIREMENTS, SKILLS, CURRENCY, MAXBUDGET, LASTDATE , STATUS, PROJECT_TYPE, CREATED_DATE) values
( 'test10','description', 'Requirements', 'JAVA,SQL', 'USD', 30.10, CURRENT_DATE, 'OPEN', 'FIXED', CURRENT_DATE);

INSERT INTO PROJECT
(TITLE, DESCRIPTION, REQUIREMENTS, SKILLS, CURRENCY, MAXBUDGET, LASTDATE , STATUS, PROJECT_TYPE, CREATED_DATE) values
( 'test11','description', 'Requirements', '.NET', 'INR', 2300.10, CURRENT_DATE, 'OPEN', 'FIXED', CURRENT_DATE);

INSERT INTO PROJECT
(TITLE, DESCRIPTION, REQUIREMENTS, SKILLS, CURRENCY, MAXBUDGET, LASTDATE , STATUS, PROJECT_TYPE, CREATED_DATE) values
( 'test12','description', 'Requirements', 'AWS,NOSQL', 'AED', 300.10, CURRENT_DATE, 'OPEN', 'FIXED', CURRENT_DATE);

INSERT INTO PROJECT
(TITLE, DESCRIPTION, REQUIREMENTS, SKILLS, CURRENCY, MAXBUDGET, LASTDATE , STATUS, PROJECT_TYPE, CREATED_DATE) values
( 'test13','description', 'Requirements', 'React,JavaScript,CSS', 'CAD', 50.10, CURRENT_DATE, 'OPEN', 'FIXED', CURRENT_DATE);

---BID DATA
INSERT INTO BID
(PROJECT_ID, BUYER, CURRENCY, BID_AMOUNT, STATUS, CREATED_DATE) values
( 10,'test Buyer1', 'USD', 31, 'OPEN', CURRENT_DATE);

INSERT INTO BID
(PROJECT_ID, BUYER, CURRENCY, BID_AMOUNT, STATUS, CREATED_DATE) values
( 10,'test Buyer2', 'USD', 32, 'OPEN', CURRENT_DATE);

INSERT INTO BID
(PROJECT_ID, BUYER, CURRENCY, BID_AMOUNT, STATUS, CREATED_DATE) values
( 10,'test Buyer3', 'USD', 43, 'OPEN', CURRENT_DATE);

INSERT INTO BID
(PROJECT_ID, BUYER, CURRENCY, BID_AMOUNT, STATUS, CREATED_DATE) values
( 11,'test Buyer1', 'INR', 2500, 'OPEN', CURRENT_DATE);

INSERT INTO BID
(PROJECT_ID, BUYER, CURRENCY, BID_AMOUNT, STATUS, CREATED_DATE) values
( 11,'test Buyer1', 'INR', 2800, 'OPEN', CURRENT_DATE);

INSERT INTO BID
(PROJECT_ID, BUYER, CURRENCY, BID_AMOUNT, STATUS, CREATED_DATE) values
( 12,'test Buyer1', 'AED', 320, 'OPEN', CURRENT_DATE);

